// ============================================================
// 教程文章清单:每篇生成独立 SEO 页面 dist/articles/<id>/index.html
// body: 文章正文 HTML(存于 src/articles/<id>.html)
// tool: 关联工具页(用于内链)
// ============================================================

export const articles = [
  {
    id: 'image-compress-guide',
    title: '图片太大怎么办?在线压缩图片的 5 个实用技巧',
    category: '图片处理',
    date: '2025-01-10',
    desc: '图片太大发不出去?本文教你 5 个免费压缩图片的技巧,从选格式、调质量到在线工具,手机电脑都适用。',
    keywords: '图片太大怎么压缩,图片压缩技巧,图片太大怎么办,压缩图片不糊',
    tool: 'image-compress',
  },
  {
    id: 'mortgage-guide',
    title: '房贷月供怎么算?等额本息和等额本金到底有什么区别',
    category: '生活计算',
    date: '2025-01-10',
    desc: '买房必看:房贷月供的计算公式、等额本息与等额本金的区别、提前还款怎么选,附在线房贷计算器。',
    keywords: '房贷月供怎么算,等额本息和等额本金的区别,房贷利率计算,提前还款',
    tool: 'mortgage',
  },
  {
    id: 'timestamp-guide',
    title: '时间戳是什么?Unix 时间戳入门与常见问题解答',
    category: '开发工具',
    date: '2025-01-10',
    desc: '程序员必懂的时间戳:什么是 Unix 时间戳、秒和毫秒怎么区分、为什么用 1970 年,附在线转换工具。',
    keywords: '时间戳是什么,unix时间戳,时间戳换算,13位时间戳',
    tool: 'timestamp',
  },
  {
    id: 'bmi-guide',
    title: 'BMI 多少算正常?中国成人标准对照表与常见误区',
    category: '生活计算',
    date: '2025-01-10',
    desc: 'BMI 指数怎么看?中国成人标准与 WHO 标准有何不同,健身人群 BMI 偏高正常吗,附在线 BMI 计算器。',
    keywords: 'bmi多少算正常,bmi标准对照表,体重指数,中国bmi标准',
    tool: 'bmi',
  },
  {
    id: 'base64-guide',
    title: 'Base64 是什么?编码原理、常见用途与在线转换',
    category: '编码转换',
    date: '2025-01-10',
    desc: 'Base64 编码入门:它是什么、为什么图片和接口里到处是它、中文乱码怎么解决,附在线编解码工具。',
    keywords: 'base64是什么,base64编码原理,base64有什么用,base64中文乱码',
    tool: 'base64',
  },
  {
    id: 'qrcode-guide',
    title: '二维码是怎么生成的?免费在线生成二维码的 3 种方法',
    category: '图片处理',
    date: '2025-01-10',
    desc: '二维码生成原理入门:QR 码如何编码信息、容错等级是什么意思,附免费在线二维码生成器使用方法。',
    keywords: '二维码怎么生成,二维码生成原理,免费二维码生成器,qr码容错',
    tool: 'qrcode',
  },
  {
    id: 'date-calc-guide',
    title: '日期差怎么算?相隔天数、工作日计算的 3 个实用场景',
    category: '生活计算',
    date: '2025-01-10',
    desc: '合同期限、倒计时、排期都离不开日期计算:自然日与工作日的区别、跨月跨年怎么算,附在线日期计算器。',
    keywords: '日期差怎么算,相隔天数计算,工作日计算,日期加减,倒计时计算',
    tool: 'date-calculator',
  },
  {
    id: 'rmb-upper-guide',
    title: '人民币大写怎么写?金额大写转换的规则与常见错误',
    category: '生活计算',
    date: '2025-01-10',
    desc: '发票、报销、合同上的金额大写怎么填?大写数字规则、零的处理、常见错误一次讲清,附在线转换工具。',
    keywords: '人民币大写怎么写,金额大写规则,发票大写,数字转大写,大写金额',
    tool: 'rmb-upper',
  },
  {
    id: 'random-picker-guide',
    title: '随机抽奖怎么做才公平?抽奖工具的使用与常见坑',
    category: '生活计算',
    date: '2025-01-10',
    desc: '年会抽奖、课堂点名、幸运观众怎么抽才公平?伪随机与真随机的区别,附免费随机抽取工具。',
    keywords: '随机抽奖,抽奖工具,公平抽奖,点名器,随机数',
    tool: 'random-picker',
  },
  {
    id: 'calori-guide',
    title: '基础代谢 BMR 和 TDEE 是什么?减肥一天到底该吃多少热量',
    category: '健康管理',
    date: '2025-01-10',
    desc: '减肥先算热量:基础代谢 BMR、每日总消耗 TDEE、热量缺口怎么算,附在线卡路里计算器与常见误区。',
    keywords: '基础代谢,bmr,tdee,减肥吃多少热量,卡路里计算,热量缺口',
    tool: 'calori',
  },
  {
    id: 'idcard-guide',
    title: '身份证号码第 18 位校验码怎么算?18 位身份证各段含义',
    category: '生活工具',
    date: '2025-01-10',
    desc: '18 位身份证号码每段代表什么?第 18 位校验码的计算公式与 X 的含义,附在线校验工具。',
    keywords: '身份证校验码,身份证号码含义,18位身份证,身份证第18位x,身份证号段',
    tool: 'idcard',
  },
  {
    id: 'luhn-guide',
    title: '银行卡号怎么验证?Luhn 算法原理与卡 BIN 识别',
    category: '生活工具',
    date: '2025-01-10',
    desc: '银行卡号最后一位是怎么算出来的?Luhn 校验算法原理、Visa/万事达/银联卡号规律,附在线校验工具。',
    keywords: '银行卡号验证,luhn算法,卡号校验,银行卡号规律,卡bin',
    tool: 'luhn',
  },
  {
    id: 'barcode-guide',
    title: '条形码和二维码有什么区别?商品条形码怎么生成',
    category: '图片处理',
    date: '2025-01-10',
    desc: '一维条码与二维码的区别、EAN-13 商品码结构、电商上架条码怎么生成,附在线条形码生成器。',
    keywords: '条形码和二维码的区别,商品条形码怎么生成,ean13是什么,条码生成',
    tool: 'barcode',
  },
  {
    id: 'typing-guide',
    title: '打字速度多少算快?WPM 标准与打字练习方法',
    category: '学习工具',
    date: '2025-01-10',
    desc: '打字速度怎么测?WPM 分级标准、中英文打字技巧与练习方法,附在线打字测速工具。',
    keywords: '打字速度多少算快,wpm标准,打字练习方法,打字速度测试',
    tool: 'typing-test',
  },
  {
    id: 'morse-guide',
    title: '摩斯电码怎么记?速记口诀与在线转换方法',
    category: '编码转换',
    date: '2025-01-10',
    desc: '摩斯电码记忆技巧:SOS 为什么是救命信号、常用字母口诀、怎么用在线工具收发摩斯电码。',
    keywords: '摩斯电码怎么记,摩斯密码口诀,sos摩斯,摩斯电码入门',
    tool: 'morse',
  },
  {
    id: 'compound-interest-guide',
    title: '复利是什么意思?复利计算与定投的力量(附计算器)',
    category: '生活计算',
    date: '2025-01-10',
    desc: '复利是世界第八大奇迹:复利公式、72 法则、定投的力量,附在线复利计算器与真实测算案例。',
    keywords: '复利是什么意思,复利公式,72法则,定投的力量,复利计算',
    tool: 'compound-interest',
  },
  {
    id: 'calculator-guide',
    title: '在线计算器怎么用?百分比、括号与四则运算技巧',
    category: '生活计算',
    date: '2025-01-10',
    desc: '计算器使用技巧:运算优先级、百分比怎么按、括号妙用、常见计算错误,附免费在线科学计算器。',
    keywords: '计算器怎么用,百分比怎么算,运算优先级,在线科学计算器,计算技巧',
    tool: 'calculator',
  },
  {
    id: 'pomodoro-guide',
    title: '番茄工作法是什么?25 分钟专注法实操与常见误区',
    category: '学习工具',
    date: '2025-01-10',
    desc: '番茄工作法完整指南:原理、25/5 节奏、使用步骤、常见误区,附免费在线番茄钟。',
    keywords: '番茄工作法,番茄钟怎么用,专注力训练,时间管理,25分钟专注',
    tool: 'countdown-timer',
  },
  {
    id: 'id-photo-guide',
    title: '证件照尺寸怎么选?一寸二寸护照签证尺寸对照表',
    category: '生活工具',
    date: '2025-01-10',
    desc: '一寸、二寸、护照、签证照片到底多大?厘米与像素对照表,拍摄前先查清楚不返工。',
    keywords: '证件照尺寸,一寸照片多大,二寸照片尺寸,护照照片尺寸,证件照像素',
    tool: 'id-photo-size',
  },
  {
    id: 'citation-guide',
    title: '参考文献格式怎么写?GB/T 7714 引用格式指南(附生成器)',
    category: '学习工具',
    date: '2025-01-10',
    desc: '论文参考文献格式完全指南:GB/T 7714-2015 规则、期刊/图书/网页各类型写法,附在线生成器。',
    keywords: '参考文献格式,参考文献怎么写,gb7714格式,论文引用格式,参考文献标注',
    tool: 'citation',
  },
  {
    id: 'salary-guide',
    title: '税后工资怎么算?个税 7 级累进税率与五险一金详解',
    category: '生活计算',
    date: '2025-01-10',
    desc: '拿到手的工资怎么算?个税起征点、7 级累进税率表、五险一金比例一次讲清,附在线税后工资计算器。',
    keywords: '税后工资怎么算,个税计算,个税税率表,五险一金比例,工资扣税',
    tool: 'salary-calculator',
  },
  {
    id: 'body-fat-guide',
    title: '体脂率多少算正常?男女标准对照与测量方法',
    category: '健康管理',
    date: '2025-01-10',
    desc: '体脂率多少正常?男女体脂标准对照表、家用测量方法、减脂与增肌的目标体脂,附在线体脂率计算器。',
    keywords: '体脂率多少正常,体脂率标准,体脂怎么测,男女体脂对照,减脂目标',
    tool: 'body-fat',
  },
]
