// ============================================================
// 工具清单:每项生成一个独立 SEO 页面 dist/<id>/index.html
// vendor: 该工具页面需要加载的本地库(相对 /vendor/)
// ============================================================

export const tools = [
  {
    id: 'qrcode',
    name: '二维码生成器',
    category: '图片工具',
    icon: '▦',
    summary: '免费在线生成二维码,支持文本、网址、WiFi 配置,可调整大小与容错率,一键下载 PNG。',
    desc: '免费在线二维码生成器,输入文字或网址即可生成二维码,支持选择尺寸与容错等级,可下载 PNG 图片,无需注册。',
    keywords: '二维码生成器,二维码在线生成,QR码生成,网址转二维码,wifi二维码',
    vendor: ['qrcode.js'],
  },
  {
    id: 'image-compress',
    name: '图片压缩',
    category: '图片工具',
    icon: '🖼',
    summary: '在线压缩 JPG/PNG/WebP 图片,可调质量与尺寸,全程浏览器本地处理,不传服务器,保护隐私。',
    desc: '免费在线图片压缩工具,支持 JPG/PNG/WebP,可调节压缩质量与输出尺寸,图片全部在本地浏览器处理,不会上传服务器。',
    keywords: '图片压缩,在线压缩图片,图片缩小,jpg压缩,png压缩',
    vendor: [],
  },
  {
    id: 'img-base64',
    name: '图片转 Base64',
    category: '图片工具',
    icon: '⇄',
    summary: '把图片一键转换为 Base64 字符串,支持 PNG/JPG/WebP,可复制到 CSS/HTML 中使用。',
    desc: '在线图片转 Base64 工具,本地转换不上传,生成 dataURL 字符串,可直接用于 CSS background 或 HTML img 标签。',
    keywords: '图片转base64,base64图片,dataurl,图片编码',
    vendor: [],
  },
  {
    id: 'json-format',
    name: 'JSON 格式化',
    category: '开发工具',
    icon: '{}',
    summary: 'JSON 格式化、压缩、校验三合一,自动缩进排版,错误提示定位,开发者必备。',
    desc: '免费在线 JSON 格式化工具,支持美化、压缩、语法校验,错误信息清晰,适合前后端开发者调试使用。',
    keywords: 'json格式化,json美化,json校验,json压缩,json在线工具',
    vendor: [],
  },
  {
    id: 'timestamp',
    name: '时间戳转换',
    category: '开发工具',
    icon: '⏱',
    summary: 'Unix 时间戳与北京时间互转,自动识别秒/毫秒,一键取当前时间戳,支持任意时区显示。',
    desc: '在线 Unix 时间戳转换工具,秒级/毫秒级自动识别,与北京时间、UTC 时间互转,复制当前时间戳一键完成。',
    keywords: '时间戳转换,unix时间戳,时间戳在线,时间戳转日期',
    vendor: [],
  },
  {
    id: 'base64',
    name: 'Base64 编解码',
    category: '编码转换',
    icon: '🔡',
    summary: 'Base64 在线编码/解码,完整支持中文与 UTF-8,一键复制结果。',
    desc: '免费在线 Base64 编解码工具,使用 UTF-8 编码正确处理中文,支持一键编码、解码与复制。',
    keywords: 'base64编码,base64解码,base64在线,中文base64',
    vendor: [],
  },
  {
    id: 'url-codec',
    name: 'URL 编解码',
    category: '编码转换',
    icon: '🔗',
    summary: 'URL 在线编码与解码,支持整个 URL 或单个参数,中文与特殊字符安全处理。',
    desc: '在线 URL 编码解码工具,快速对中文、空格、特殊字符进行 encodeURIComponent / decodeURIComponent 转换。',
    keywords: 'url编码,url解码,urlencode,urldecode,网址编码',
    vendor: [],
  },
  {
    id: 'md5',
    name: 'MD5 加密',
    category: '编码转换',
    icon: '🔐',
    summary: '在线 MD5 加密计算,支持中文 UTF-8,附带 SHA-256 哈希,大写/小写一键切换。',
    desc: '免费在线 MD5 加密工具,正确按 UTF-8 计算中文 MD5,同时提供 SHA-256,结果支持大写与小写。',
    keywords: 'md5加密,md5在线,md5计算,md5解密校验,sha256',
    vendor: ['md5.min.js'],
  },
  {
    id: 'word-count',
    name: '字数统计',
    category: '文本处理',
    icon: '🔢',
    summary: '实时统计中文字数、字符数、单词数、行数与段落数,支持粘贴长文分析。',
    desc: '免费在线字数统计工具,实时统计中文字数、字符数(含/不含空格)、英文单词数、行数、段落数,适合写作与投稿。',
    keywords: '字数统计,在线字数,中文字数统计,文章字数,字符统计',
    vendor: [],
  },
  {
    id: 'text-tools',
    name: '文本处理',
    category: '文本处理',
    icon: '✂',
    summary: '文本去重、排序、去除空行、大小写转换,批量整理文本一键完成。',
    desc: '免费在线文本处理工具,支持按行去重、排序、删除空行、大小写转换,批量整理文本数据。',
    keywords: '文本去重,文本排序,去空行,大小写转换,文本整理',
    vendor: [],
  },
  {
    id: 'text-diff',
    name: '文本对比',
    category: '文本处理',
    icon: '⇵',
    summary: '两段文本逐行对比,新增/删除/修改高亮显示,支持粘贴代码与文档。',
    desc: '在线文本对比工具,基于逐行 Diff 算法高亮显示新增、删除与修改内容,适合对比代码与文档版本。',
    keywords: '文本对比,文本diff,代码对比,文件对比,在线diff',
    vendor: ['diff.min.js'],
  },
  {
    id: 'password',
    name: '随机密码生成',
    category: '安全工具',
    icon: '🔑',
    summary: '高强度随机密码生成器,自定义长度与字符组合,使用密码学安全随机源,附强度评估。',
    desc: '免费在线随机密码生成器,基于 crypto.getRandomValues 密码学安全随机源,支持大小写、数字、符号组合与强度评估。',
    keywords: '随机密码生成,密码生成器,强密码,随机密码,密码工具',
    vendor: [],
  },
  {
    id: 'uuid',
    name: 'UUID 生成器',
    category: '开发工具',
    icon: '🆔',
    summary: '批量生成 UUID v4,支持大写、去横线格式,一次生成多个,开发者接口测试必备。',
    desc: '在线 UUID 生成器,基于 crypto.randomUUID 批量生成 v4 格式,支持大写与去横线变体,一键复制全部。',
    keywords: 'uuid生成,uuid v4,guid生成,随机id,批量uuid',
    vendor: [],
  },
  {
    id: 'regex-tester',
    name: '正则表达式测试',
    category: '开发工具',
    icon: '∑',
    summary: '在线正则测试工具,实时高亮匹配结果,支持修饰符,附带常用正则速查。',
    desc: '免费在线正则表达式测试工具,输入正则与文本实时高亮匹配位置,支持 g/i/m/s 修饰符,含常用正则示例。',
    keywords: '正则表达式测试,正则在线,regex测试,正则匹配,常用正则',
    vendor: [],
  },
  {
    id: 'base-converter',
    name: '进制转换',
    category: '开发工具',
    icon: '101',
    summary: '十进制、二进制、八进制、十六进制互转,支持超大整数(BigInt),无精度丢失。',
    desc: '在线进制转换工具,支持 2/8/10/16 进制互转,使用 BigInt 支持超大整数,结果实时联动。',
    keywords: '进制转换,二进制转换,十六进制,十进制转二进制,在线进制',
    vendor: [],
  },
  {
    id: 'color-converter',
    name: '颜色转换',
    category: '设计工具',
    icon: '🎨',
    summary: 'HEX、RGB、HSL 颜色互转,实时色块预览,支持透明度,设计师配色好帮手。',
    desc: '免费在线颜色转换工具,HEX/RGB/HSL 三种格式实时互转并预览色块,支持透明度,附带调色板。',
    keywords: '颜色转换,hex转rgb,rgb转hex,颜色代码,在线调色板',
    vendor: [],
  },
  {
    id: 'markdown',
    name: 'Markdown 编辑器',
    category: '文本处理',
    icon: '📝',
    summary: '在线 Markdown 编辑与实时预览,支持表格、代码块、流程图语法,一键复制 HTML。',
    desc: '免费在线 Markdown 编辑器,左侧编辑右侧实时预览,支持标题、表格、代码块等语法,可一键复制渲染后的 HTML。',
    keywords: 'markdown编辑器,markdown在线,markdown预览,md转html,在线md',
    vendor: ['marked.min.js'],
  },
  {
    id: 'mortgage',
    name: '房贷计算器',
    category: '生活计算',
    icon: '🏠',
    summary: '等额本息/等额本金月供计算,支持公积金与组合贷款,含首月月供与利息明细,买房必备。',
    desc: '免费在线房贷计算器,支持等额本息与等额本金两种还款方式,输入贷款金额、利率与年限即可得到月供、总利息、还款总额及每月还款明细。',
    keywords: '房贷计算器,房贷计算,月供计算,等额本息,等额本金,公积金贷款计算器',
    vendor: [],
  },
  {
    id: 'bmi',
    name: 'BMI 计算器',
    category: '生活计算',
    icon: '⚖',
    summary: '输入身高体重秒算 BMI,对照中国标准给出偏瘦/正常/超重/肥胖评级与健康建议。',
    desc: '免费在线 BMI 体重指数计算器,按中国标准(18.5~23.9 正常)给出评级与健康建议,还包含理想体重参考。',
    keywords: 'bmi计算,bmi计算器,体重指数,身高体重计算,体质指数',
    vendor: [],
  },
  {
    id: 'age',
    name: '年龄计算器',
    category: '生活计算',
    icon: '🎂',
    summary: '出生日期一键换算周岁、虚岁、出生天数与距下次生日倒计时,附带生肖与星座。',
    desc: '免费在线年龄计算器,输入出生日期即可得到周岁、虚岁、已出生天数、距离下次生日天数,并附生肖与星座信息。',
    keywords: '年龄计算器,周岁计算,虚岁计算,出生天数,生日倒计时',
    vendor: [],
  },
  {
    id: 'percentage',
    name: '百分比计算器',
    category: '生活计算',
    icon: '％',
    summary: '求占比、求增长/下降百分比、百分比增减,三种常用模式一键计算。',
    desc: '免费在线百分比计算器,支持「X 的 Y% 是多少」「X 占 Y 的百分之几」「增加/减少 Y%」三种模式,适合购物折扣、涨薪、数据分析。',
    keywords: '百分比计算器,百分比计算,占比计算,折扣计算,涨幅计算',
    vendor: [],
  },
  {
    id: 'unit-converter',
    name: '单位换算',
    category: '生活计算',
    icon: '📏',
    summary: '长度、重量、温度、面积、体积、速度、存储、时间八大类单位即时换算,支持温度公式换算。',
    desc: '免费在线单位换算器,支持长度、重量、温度、面积、体积、速度、数据存储、时间八大类单位换算,温度支持摄氏/华氏/开氏公式转换。',
    keywords: '单位换算,长度换算,重量换算,温度换算,面积换算,单位转换器',
    vendor: [],
  },
  {
    id: 'zodiac',
    name: '生肖星座查询',
    category: '生活计算',
    icon: '🐲',
    summary: '输入生日查询生肖、星座、天干地支年,附生肖性格简析与星座日期对照。',
    desc: '免费在线生肖星座查询工具,输入出生日期即可查询属相、星座与天干地支纪年,附生肖性格特点与十二星座日期表。',
    keywords: '生肖查询,星座查询,属相查询,十二星座,生辰查询',
    vendor: [],
  },
  {
    id: 'date-calculator',
    name: '日期计算器',
    category: '生活计算',
    icon: '📅',
    summary: '两个日期相隔多少天、某日期加 N 天是哪天,支持工作日统计,日期差一键算清。',
    desc: '免费在线日期计算器,计算两个日期之间的天数、周数与工作日,也可计算某日期加上 N 天后的日期,适合倒计时、合同期限与排期。',
    keywords: '日期计算器,日期差,相隔多少天,天数计算,日期加减',
    vendor: [],
  },
  {
    id: 'rmb-upper',
    name: '人民币大写转换',
    category: '生活计算',
    icon: '¥',
    summary: '数字金额一键转人民币大写,支持到分,发票、报销、合同金额必备。',
    desc: '免费在线人民币大写转换工具,把数字金额转换为标准中文大写(壹贰叁…圆角分整),支持到分位,适用于发票、报销单与合同。',
    keywords: '人民币大写,数字转大写,金额大写转换,发票大写,报销大写',
    vendor: [],
  },
  {
    id: 'random-picker',
    name: '随机抽取器',
    category: '生活计算',
    icon: '🎲',
    summary: '名单随机抽取、抽奖、点名,支持抽取数量与重复开关,附随机数生成。',
    desc: '免费在线随机抽取工具,输入名单即可抽奖/点名,可设置抽取人数与是否允许重复,另附随机整数生成功能。',
    keywords: '随机抽取,抽奖工具,点名器,随机数生成器,随机选择',
    vendor: [],
  },
  {
    id: 'calori',
    name: '卡路里计算器',
    category: '健康管理',
    icon: '🔥',
    summary: '基础代谢 BMR 与每日消耗 TDEE 计算,含减脂/保持/增肌目标热量,科学管理体重。',
    desc: '免费在线卡路里计算器,基于 Mifflin-St Jeor 公式计算基础代谢 BMR 与每日总消耗 TDEE,按目标给出减脂、保持、增肌的每日热量建议。',
    keywords: '卡路里计算器,基础代谢计算,bmr计算,tdee,热量计算,减肥热量',
    vendor: [],
  },
  {
    id: 'idcard',
    name: '身份证号码校验',
    category: '生活工具',
    icon: '🪪',
    summary: '18 位身份证号码在线校验,验证校验码与出生日期,解析性别、出生地、星座生肖。',
    desc: '免费在线身份证号码校验工具,验证 18 位身份证的格式、出生日期与第 18 位校验码,并解析出生日期、性别、户籍省市、星座生肖。',
    keywords: '身份证校验,身份证号码查询,身份证验证,身份证号解析,18位身份证',
    vendor: [],
  },
  {
    id: 'caesar',
    name: '凯撒密码加密',
    category: '编码转换',
    icon: '🗝',
    summary: '凯撒密码在线加密解密,支持任意位移,附原理说明,适合学习与趣味加密。',
    desc: '免费在线凯撒密码工具,对英文字母按任意位移加密/解密,支持大小写,并附凯撒密码原理与破解方法说明。',
    keywords: '凯撒密码,凯撒加密,密码加密工具,位移密码,caesar cipher',
    vendor: [],
  },
  {
    id: 'morse',
    name: '摩斯电码转换',
    category: '编码转换',
    icon: '📡',
    summary: '文本与摩斯电码互转,支持字母数字与标点,附完整对照表与听力练习。',
    desc: '免费在线摩斯电码转换工具,文字与摩斯电码双向互转,支持 A-Z、0-9 与常用标点,附完整对照表。',
    keywords: '摩斯电码,摩斯密码转换,摩斯电码翻译,morse code,电报码',
    vendor: [],
  },
  {
    id: 'http-status',
    name: 'HTTP 状态码速查',
    category: '开发工具',
    icon: '🌐',
    summary: 'HTTP 状态码大全,1xx~5xx 分类速查,含含义、常见场景与排查建议,开发者必备。',
    desc: 'HTTP 状态码在线速查表,覆盖 1xx-5xx 全部常见状态码,解释含义与常见触发场景,适合开发调试与面试复习。',
    keywords: 'http状态码,状态码查询,404是什么意思,500错误,http状态码大全',
    vendor: [],
  },
  {
    id: 'timezone',
    name: '世界时区转换',
    category: '开发工具',
    icon: '🕐',
    summary: '全球主要城市时区互转,一键换算两地时间与时差,出差开会不再算错时间。',
    desc: '免费在线世界时区转换工具,支持北京、伦敦、纽约、东京等主要城市互转,显示两地时间与时差(UTC 偏移)。',
    keywords: '时区转换,世界时间,时差计算,时间换算,utc时间',
    vendor: [],
  },
  {
    id: 'compound-interest',
    name: '复利计算器',
    category: '生活计算',
    icon: '📈',
    summary: '复利终值与定投收益计算,支持每年追加投入,直观展示时间与复利的威力。',
    desc: '免费在线复利计算器,计算本金按复利增长的终值,支持每年定投追加,含逐年明细表,适合理财规划与教育金测算。',
    keywords: '复利计算器,定投计算,投资收益计算,复利终值,理财计算器',
    vendor: [],
  },
  {
    id: 'url-parse',
    name: 'URL 解析器',
    category: '开发工具',
    icon: '🧩',
    summary: '网址一键拆解:协议、域名、端口、路径、查询参数表格化展示,接口调试必备。',
    desc: '免费在线 URL 解析工具,把网址拆解为协议、主机、端口、路径、查询参数与哈希,参数以表格展示,开发者调试接口常用。',
    keywords: 'url解析,网址解析,url参数提取,url拆分,链接解析',
    vendor: [],
  },
  {
    id: 'calculator',
    name: '在线计算器',
    category: '生活计算',
    icon: '➗',
    summary: '支持四则运算、括号、百分比的科学计算器,键盘输入与按钮双支持,界面简洁。',
    desc: '免费在线科学计算器,支持加减乘除、括号、百分比与小数点,可用键盘直接输入,适合日常计算与公式验证。',
    keywords: '计算器,在线计算器,科学计算器,计算器在线使用',
    vendor: [],
  },
  {
    id: 'barcode',
    name: '条形码生成器',
    category: '图片工具',
    icon: '〓',
    summary: '在线生成商品条形码,支持 EAN-13、CODE128、EAN-8 等格式,电商上架必备,可下载 PNG。',
    desc: '免费在线条形码生成器,支持 EAN-13、EAN-8、CODE128、CODE39 等格式,可自定义尺寸与是否显示数字,一键下载 PNG,电商上架与商品管理常用。',
    keywords: '条形码生成,条形码生成器,ean13,code128,商品条码生成',
    vendor: ['JsBarcode.all.min.js'],
  },
  {
    id: 'luhn',
    name: '银行卡号校验',
    category: '生活工具',
    icon: '💳',
    summary: '银行卡/信用卡号 Luhn 算法校验,识别 Visa、万事达、银联等发卡行,支付开发与自查必备。',
    desc: '免费在线银行卡号校验工具,基于 Luhn 算法验证卡号合法性,并按卡 BIN 识别 Visa、Mastercard、银联、美国运通等发卡机构与卡号长度。',
    keywords: '银行卡号校验,信用卡号验证,luhn算法,银行卡号识别,卡bin查询',
    vendor: [],
  },
  {
    id: 'typing-test',
    name: '打字测速',
    category: '学习工具',
    icon: '⌨',
    summary: '在线打字速度测试,实时统计 WPM、正确率与用时,含中文与英文两种模式。',
    desc: '免费在线打字速度测试工具,提供中文与英文测试文本,实时统计每分钟字数 WPM、正确率与用时,练习打字必备。',
    keywords: '打字测试,打字速度测试,打字测速,在线打字练习,wpm',
    vendor: [],
  },
  {
    id: 'tts',
    name: '文字转语音',
    category: '生活工具',
    icon: '🔊',
    summary: '在线文字朗读,支持中文多种音色、语速与音量调节,浏览器本地合成,无需上传。',
    desc: '免费在线文字转语音工具,调用浏览器语音合成,支持中文普通话多种音色,可调语速与音量,输入文字即可朗读,适合听书与校对。',
    keywords: '文字转语音,在线朗读,语音合成,tts,文字朗读',
    vendor: [],
  },
  {
    id: 'random-name',
    name: '随机起名',
    category: '生活工具',
    icon: '👶',
    summary: '随机名字生成器,可选百家姓、性别风格与单双字,宝宝起名、网名创作灵感必备。',
    desc: '免费在线随机起名工具,内置百家姓与男女风格字库,支持单字/双字、按性别生成,一键批量生成多个候选名,宝宝起名与网名创作都能用。',
    keywords: '随机起名,名字生成器,宝宝起名,起名工具,取名',
    vendor: [],
  },
  {
    id: 'emoji',
    name: 'Emoji 大全',
    category: '字符符号',
    icon: '😀',
    summary: '常用 emoji 表情大全,分类速查一键复制,聊天、文案、标题装饰必备。',
    desc: '免费 Emoji 表情大全,笑脸、手势、动物、食物、旅行等分类速查,点击即可复制到剪贴板,写文案做标题都方便。',
    keywords: 'emoji大全,emoji表情,表情符号大全,emoji复制,特殊表情',
    vendor: [],
  },
  {
    id: 'symbols',
    name: '特殊符号大全',
    category: '字符符号',
    icon: '✳',
    summary: '特殊符号大全:数学符号、货币、箭头、星形心形等分类一键复制,起名文案必备。',
    desc: '免费特殊符号大全,涵盖数学、货币、箭头、星形、心形、标点等常用符号,分类浏览点击复制,写文案、起标题、网名必备。',
    keywords: '特殊符号大全,符号复制,数学符号,箭头符号,心形符号',
    vendor: [],
  },
  {
    id: 'kaomoji',
    name: '颜文字大全',
    category: '字符符号',
    icon: '◕‿◕',
    summary: '颜文字(kaomoji)大全:开心、卖萌、悲伤等分类一键复制,日式表情爱好者必备。',
    desc: '免费颜文字大全,收集开心、卖萌、悲伤、生气、无奈等场景的日式颜文字,点击一键复制,聊天与文案装饰神器。',
    keywords: '颜文字,颜文字大全,kaomoji,表情符号,卖萌符号',
    vendor: [],
  },
]
