// ============================================================
// 工具清单:每项生成一个独立 SEO 页面 dist/<id>/index.html
// vendor: 该工具页面需要加载的本地库(相对 /vendor/)
// ============================================================

export const tools = [
  {
    id: 'qrcode',
    name: '二维码生成器',
    category: '图片工具',
    icon: '▦',
    summary: '免费在线生成二维码,支持文本、网址、WiFi 配置,可调整大小与容错率,一键下载 PNG。',
    desc: '免费在线二维码生成器,输入文字或网址即可生成二维码,支持选择尺寸与容错等级,可下载 PNG 图片,无需注册。',
    keywords: '二维码生成器,二维码在线生成,QR码生成,网址转二维码,wifi二维码',
    vendor: ['qrcode.js'],
  },
  {
    id: 'image-compress',
    name: '图片压缩',
    category: '图片工具',
    icon: '🖼',
    summary: '在线压缩 JPG/PNG/WebP 图片,可调质量与尺寸,全程浏览器本地处理,不传服务器,保护隐私。',
    desc: '免费在线图片压缩工具,支持 JPG/PNG/WebP,可调节压缩质量与输出尺寸,图片全部在本地浏览器处理,不会上传服务器。',
    keywords: '图片压缩,在线压缩图片,图片缩小,jpg压缩,png压缩',
    vendor: [],
  },
  {
    id: 'img-base64',
    name: '图片转 Base64',
    category: '图片工具',
    icon: '⇄',
    summary: '把图片一键转换为 Base64 字符串,支持 PNG/JPG/WebP,可复制到 CSS/HTML 中使用。',
    desc: '在线图片转 Base64 工具,本地转换不上传,生成 dataURL 字符串,可直接用于 CSS background 或 HTML img 标签。',
    keywords: '图片转base64,base64图片,dataurl,图片编码',
    vendor: [],
  },
  {
    id: 'json-format',
    name: 'JSON 格式化',
    category: '开发工具',
    icon: '{}',
    summary: 'JSON 格式化、压缩、校验三合一,自动缩进排版,错误提示定位,开发者必备。',
    desc: '免费在线 JSON 格式化工具,支持美化、压缩、语法校验,错误信息清晰,适合前后端开发者调试使用。',
    keywords: 'json格式化,json美化,json校验,json压缩,json在线工具',
    vendor: [],
  },
  {
    id: 'timestamp',
    name: '时间戳转换',
    category: '开发工具',
    icon: '⏱',
    summary: 'Unix 时间戳与北京时间互转,自动识别秒/毫秒,一键取当前时间戳,支持任意时区显示。',
    desc: '在线 Unix 时间戳转换工具,秒级/毫秒级自动识别,与北京时间、UTC 时间互转,复制当前时间戳一键完成。',
    keywords: '时间戳转换,unix时间戳,时间戳在线,时间戳转日期',
    vendor: [],
  },
  {
    id: 'base64',
    name: 'Base64 编解码',
    category: '编码转换',
    icon: '🔡',
    summary: 'Base64 在线编码/解码,完整支持中文与 UTF-8,一键复制结果。',
    desc: '免费在线 Base64 编解码工具,使用 UTF-8 编码正确处理中文,支持一键编码、解码与复制。',
    keywords: 'base64编码,base64解码,base64在线,中文base64',
    vendor: [],
  },
  {
    id: 'url-codec',
    name: 'URL 编解码',
    category: '编码转换',
    icon: '🔗',
    summary: 'URL 在线编码与解码,支持整个 URL 或单个参数,中文与特殊字符安全处理。',
    desc: '在线 URL 编码解码工具,快速对中文、空格、特殊字符进行 encodeURIComponent / decodeURIComponent 转换。',
    keywords: 'url编码,url解码,urlencode,urldecode,网址编码',
    vendor: [],
  },
  {
    id: 'md5',
    name: 'MD5 加密',
    category: '编码转换',
    icon: '🔐',
    summary: '在线 MD5 加密计算,支持中文 UTF-8,附带 SHA-256 哈希,大写/小写一键切换。',
    desc: '免费在线 MD5 加密工具,正确按 UTF-8 计算中文 MD5,同时提供 SHA-256,结果支持大写与小写。',
    keywords: 'md5加密,md5在线,md5计算,md5解密校验,sha256',
    vendor: ['md5.min.js'],
  },
  {
    id: 'word-count',
    name: '字数统计',
    category: '文本处理',
    icon: '🔢',
    summary: '实时统计中文字数、字符数、单词数、行数与段落数,支持粘贴长文分析。',
    desc: '免费在线字数统计工具,实时统计中文字数、字符数(含/不含空格)、英文单词数、行数、段落数,适合写作与投稿。',
    keywords: '字数统计,在线字数,中文字数统计,文章字数,字符统计',
    vendor: [],
  },
  {
    id: 'text-tools',
    name: '文本处理',
    category: '文本处理',
    icon: '✂',
    summary: '文本去重、排序、去除空行、大小写转换,批量整理文本一键完成。',
    desc: '免费在线文本处理工具,支持按行去重、排序、删除空行、大小写转换,批量整理文本数据。',
    keywords: '文本去重,文本排序,去空行,大小写转换,文本整理',
    vendor: [],
  },
  {
    id: 'text-diff',
    name: '文本对比',
    category: '文本处理',
    icon: '⇵',
    summary: '两段文本逐行对比,新增/删除/修改高亮显示,支持粘贴代码与文档。',
    desc: '在线文本对比工具,基于逐行 Diff 算法高亮显示新增、删除与修改内容,适合对比代码与文档版本。',
    keywords: '文本对比,文本diff,代码对比,文件对比,在线diff',
    vendor: ['diff.min.js'],
  },
  {
    id: 'password',
    name: '随机密码生成',
    category: '安全工具',
    icon: '🔑',
    summary: '高强度随机密码生成器,自定义长度与字符组合,使用密码学安全随机源,附强度评估。',
    desc: '免费在线随机密码生成器,基于 crypto.getRandomValues 密码学安全随机源,支持大小写、数字、符号组合与强度评估。',
    keywords: '随机密码生成,密码生成器,强密码,随机密码,密码工具',
    vendor: [],
  },
  {
    id: 'uuid',
    name: 'UUID 生成器',
    category: '开发工具',
    icon: '🆔',
    summary: '批量生成 UUID v4,支持大写、去横线格式,一次生成多个,开发者接口测试必备。',
    desc: '在线 UUID 生成器,基于 crypto.randomUUID 批量生成 v4 格式,支持大写与去横线变体,一键复制全部。',
    keywords: 'uuid生成,uuid v4,guid生成,随机id,批量uuid',
    vendor: [],
  },
  {
    id: 'regex-tester',
    name: '正则表达式测试',
    category: '开发工具',
    icon: '∑',
    summary: '在线正则测试工具,实时高亮匹配结果,支持修饰符,附带常用正则速查。',
    desc: '免费在线正则表达式测试工具,输入正则与文本实时高亮匹配位置,支持 g/i/m/s 修饰符,含常用正则示例。',
    keywords: '正则表达式测试,正则在线,regex测试,正则匹配,常用正则',
    vendor: [],
  },
  {
    id: 'base-converter',
    name: '进制转换',
    category: '开发工具',
    icon: '101',
    summary: '十进制、二进制、八进制、十六进制互转,支持超大整数(BigInt),无精度丢失。',
    desc: '在线进制转换工具,支持 2/8/10/16 进制互转,使用 BigInt 支持超大整数,结果实时联动。',
    keywords: '进制转换,二进制转换,十六进制,十进制转二进制,在线进制',
    vendor: [],
  },
  {
    id: 'color-converter',
    name: '颜色转换',
    category: '设计工具',
    icon: '🎨',
    summary: 'HEX、RGB、HSL 颜色互转,实时色块预览,支持透明度,设计师配色好帮手。',
    desc: '免费在线颜色转换工具,HEX/RGB/HSL 三种格式实时互转并预览色块,支持透明度,附带调色板。',
    keywords: '颜色转换,hex转rgb,rgb转hex,颜色代码,在线调色板',
    vendor: [],
  },
  {
    id: 'markdown',
    name: 'Markdown 编辑器',
    category: '文本处理',
    icon: '📝',
    summary: '在线 Markdown 编辑与实时预览,支持表格、代码块、流程图语法,一键复制 HTML。',
    desc: '免费在线 Markdown 编辑器,左侧编辑右侧实时预览,支持标题、表格、代码块等语法,可一键复制渲染后的 HTML。',
    keywords: 'markdown编辑器,markdown在线,markdown预览,md转html,在线md',
    vendor: ['marked.min.js'],
  },
]
